export type Hex = string
export type Byte = string | number
export type Byte2 = string | number
export type Byte4 = string | number
export type Byte20 = string
export type Byte24 = string
export type Byte32 = string
export type Bytes = string
export type Address = string
export type Capacity = bigint
